---
- name: Importing google gpg
  shell:
    cmd: curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add google repository
  apt_repository:
    filename: google-k8s-repo
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'

- name: Install kubeadm stuffs
  apt:
    pkg:
      - "kubelet={{ kube_version }}-00"
      - "kubeadm={{ kube_version }}-00"
      - "kubectl={{ kube_version }}-00"
    state: present